

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
      sh "flutter clean"
      sh "flutter build apk --release --flavor Production --target lib/main_production.dart --no-tree-shake-icons"
      firebase_app_distribution(
        app: "1:471595328435:android:21650ef6b1cc07b91961c6",
        firebase_cli_token:"1//03SJv_7aqPQIRCgYIARAAGAMSNwF-L9IrV0JXU4RgjEKwR1o9OGiw8GblbClhTTbx5GM6lKUz_V6vQ8L1kY3AldfAdHwmYXfqHjI",
        android_artifact_type:"APK",
        android_artifact_path:"../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "zaynabsrour1991@gmail.com",
        release_notes:"First Fastalne Firebase Distribution Youtube Video!"
      )
  end

end
